### PR TITLE
Updated content for 2016 site

### PR DESCRIPTION
**Pull request by Coraellation**
Almost all text is changed on the front page.

### CODE REVIEW

**Comment by Coraellation** [comment]
@icechen1 PTAL :relaxed:  Biggest question: when are we opening applications? I wrote May in the FAQ, but this might not exactly be correct.

**Comment by itsbilal** [comment]
@Coraellation We were hoping for early April - but I'll check with web to see what their timeline is.

**Comment by Coraellation** [comment]
Thank you @itsbilal ! Much appreciated.

**Comment by yucombinator** [comment]
:+1:

**Pull request merged**
