### PR TITLE
Migrate 2016 Site to Main Site

### PR DESCRIPTION
**Pull request by Coraellation**
Several file changes including:
- Copying entire old site into the 2015 folder
- Move all files in the 2016 folder into the root folder
- Keep all other files in the main folder (ie. transparency_report.html, 404.html, other pdfs)
- Test on my machine, and is working!

### CODE REVIEW

**Comment by Coraellation** [comment]
@davepagurek @icechen1 PTAL -> A really big change, so I thought I'd run it through with you guys and anyone else who looks at this. It works on my machine, but hoping I didn't overlook anything.

**Comment by yucombinator** [comment]
That number of change looks scary

**Comment by Coraellation** [comment]
Yes! But they're all just moving files in and out of folders. But maybe test out the branch as well!

**Comment by yucombinator** [comment]
It seems like it works fine here as well :+1:

**Comment by yucombinator** [comment]
I like that Simon pic. can we keep it? @xmfan

**Comment by Coraellation** [comment]
2016 SITE IS OFFICIALLY UP and ... it broke

**Comment by Coraellation** [comment]
False alarm! :relieved: thanks @icechen1 for clearing the cache

**Pull request merged**
