### PR TITLE
New Pic

### PR DESCRIPTION
**Pull request by Coraellation**

### CODE REVIEW

**Comment by Coraellation** [comment]
@davepagurek Just wanted to make sure I'm placing it in the right folder and is the right format

**Comment by pbardea** [comment]
@Coraellation to show up on the site, you just need to add your name and path to the image in `2016/data/team.json` as well. But the picture location looks good! :D

**Comment by yucombinator** [comment]
Also please scale the pic to about 500px in width and run it through an optimization tool like imgageoptim.

**Comment by yucombinator** [comment]
2mb pic is going to make the site load pretty slowly for people with crappy internet (like me!)

**Comment by Coraellation** [comment]
@icechen1 No worries, I gotchu! 53 KB now.

**Comment by pbardea** [comment]
:+1:

**Comment by yucombinator** [comment]
LGTM

**Pull request merged**
