### PR TITLE
Shrink team pics

### PR DESCRIPTION
**Pull request by yucombinator**

### CODE REVIEW

**Comment by Deon** [comment]
Can we bring these all down to ~ 100px or something?

**Comment by yucombinator** [comment]
Dave might use the same pics to create the team members page. Besides, the pics are about 20kb's each now. Hardly noticible

**Comment by yucombinator** [comment]
It's currently 500-700px

**Comment by Deon** [comment]
Okay, sounds good. Bring this in for now and I'll take a look at future optimizations later. :+1:

**Pull request merged**
